host: localhost
port: 27017
db: tweet_db
debug: true
replicaset: false
tweet_folder: tweets
collections:
  - name: tweets
    indices:
      - tweetid
      - timestamp
  - name: hashtags
    indices:
      - count