host: localhost
port: 27017
db: tweet_db
replicaset: false
tweet_folder: tweets
collections:
  - name: tweets
    indices:
      - tweet_id
      - publish_date
  - name: hashtags
    indices:
      - count